---
title: "Shape Variation"
author: "Suzy"
date: '2022-05-23'
output: html_document
---


```{r test}
# library
# install.packages(ggridges) package not found
remotes::install_github("wilkelab/ggridges")
library(ggridges)
library(ggplot2)
library(dplyr)
library(tidyr)
library(forcats)

# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/zonination/perceptions/master/probly.csv", header=TRUE, sep=",")
data <- data %>% 
  gather(key="text", value="value") %>%
  mutate(text = gsub("\\.", " ",text)) %>%
  mutate(value = round(as.numeric(value),0)) %>%
  filter(text %in% c("Almost Certainly","Very Good Chance","We Believe","Likely","About Even", "Little Chance", "Chances Are Slight", "Almost No Chance"))

# Plot
data %>%
  mutate(text = fct_reorder(text, value)) %>%
  ggplot( aes(y=text, x=value,  fill=text)) +
    geom_density_ridges(alpha=0.6, stat="binline", bins=20) +
    theme_ridges() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    ) +
    xlab("") +
    ylab("Assigned Probability (%)")
```

## Creating new data set


```{r data set}
parole_adj_adv <- subset(parole_adj_adv, select = -pubtitle)
parole_adj_adv <- subset(parole_adj_adv, select = -pos)

variation_data <- parole_adj_adv %>%
  ungroup() %>%
  filter(word %in% c("violent", "parole", "probation", "dangerous", "drug")) %>%
  group_by(word, year) %>%
  summarise(count_total = sum(count)) %>%
  arrange(year)

```



```{r Plot}

# Plot
variation_data %>%
  mutate(text = fct_reorder(word, count_total)) %>%
  ggplot( aes(y=word, x=count_total,  fill=text)) +
    geom_density_ridges(alpha=0.6, stat="binline", bins=30) +
    theme_ridges() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.3, "lines"),
      strip.text.x = element_text(size = 10)
    ) +
    xlab("") +
    ylab("Assigned Probability (%)")

```

```{r stacked line plot}
# Libraries
library(ggplot2)
library(dplyr)
library(viridis)
library(hrbrthemes)
devtools::install_github("ropensci/plotly")
library(plotly)

# Plot
p <- variation_data %>% 
  ggplot( aes(x=year, y=count_total, fill=word, text=word)) +
    geom_area( ) +
    scale_fill_viridis(discrete = TRUE) +
    theme(legend.position="none") +
    ggtitle("Popularity of Certain Words in the past 20 years") +
    theme_ipsum() +
    theme(legend.position="none")

# Turn it interactive
p <- ggplotly(p, tooltip="text")
p

# save the widget
# library(htmlwidgets)
# saveWidget(p, file=paste0( getwd(), "/HtmlWidget/ggplotlyStackedareachart.html"))
```

##General Plot of Negative and Positive Sentiments

#Creating the Data Set

```{r general dataset}
variation_data2 <- parole_adj_adv %>%
  ungroup() %>%
  group_by(sentiment, year) %>%
  summarise(count_total = sum(count)) %>%
  filter(sentiment %in% c("positive", "negative")) %>%
  arrange(year)
```
#Create secondary filled line plot


```{r Plot #2}
plot2 <- variation_data2 %>% 
  ggplot( aes(x=year, y=count_total, fill=sentiment, text=sentiment)) +
    geom_area() +
    scale_fill_viridis(discrete = TRUE) +
    theme(legend.position="none") +
    ggtitle("Sentiments Over the Course of 20 years") +
    #theme_ipsum() +
    theme_minimal() +
    #theme_classic() +
  labs(
    x = "Year", 
    y = "Frequency"
    ) +
    theme(legend.position="none")


# Turn it interactive
plot2 <- ggplotly(plot2, tooltip="text")
plot2

# save the widget
# library(htmlwidgets)
saveWidget(plot2, file="sentiment_stacked_area_chart.html")
```

