---
title: "text_analyses"
output: html_document
date: '2022-05-04'
---

```{r package}
library(readr)
library(tidytext)
library(stringr)
library(tidyverse) 
library(skimr)
library(robotstxt)
library(rvest) 
```

```{r read-data-1}
parole_data <- read_csv("data/proquest_1.csv")
```

```{r read-data-2}
parole_text_1 <- read.delim("data/proquest_2.txt", header = TRUE)
colnames(parole_text_1)[1] <- "id"
```

```{r extract document id}

pattern <- paste(parole_data$StoreId, collapse = "|") # all possible patterns

parole_text_1$StoreId <- as.numeric(str_extract(string = parole_text_1$id, pattern = pattern))

parole_text_article <- parole_text_1 %>% fill(StoreId)

parole_text_article_df <- left_join(parole_text_article, 
                           parole_data,
                           by = "StoreId")

```


```{r change-column name}
colnames(parole_text_article_df)[1] <- "text"
```

```{r clean-data}
parole_sub <- parole_text_article_df[-str_which(parole_text_article_df$text, pattern = "ProQuest document ID:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Publication info:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "https:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Author:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Abstract:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Subject:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Location:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Company / organization:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Title:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Publication title:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Publication year:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Publication date:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Publication subject:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "First page:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Publisher:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Place of publication:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Country of publication:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Language of publication:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "ISSN:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Source type:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Document type:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Copyright:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Last updated:"),]
parole_sub <- parole_sub[-str_which(parole_sub$text, pattern = "Database:"),]
parole_sub <- parole_sub[-(str_which(parole_sub$text, pattern = "Full text:")-1),]
```

```{r}
prepare_sub <- str_which(parole_sub$text, pattern = "Full text:")-1
parole_sub <- parole_sub[-prepare_sub[-1],]
```


```{r keep-text}
#full_text_loc <- str_locate(parole_text_1$text, "Full text:")
#which(full_text_loc[,1] == '1')

#subject_loc <- str_detect(parole_text_1$id, #"____________________________________________________________")


#start_end <- data.frame(start = rep(10, 519), end = which(subject_loc==TRUE) + 2)
#which(subject_loc==TRUE) + 2
```

