---
title: "word_analysis_2"
author: "Suzy"
date: '2022-05-10'
output: html_document
---

## R Markdown

```{r ndividual Words and their parts of speech}
#install.packages("SnowballC")
#install.packages("dplyr")
library(SnowballC)
library(dplyr)
library(janitor)
library(tidytext)



parole_sub2 <- parole_sub %>%
  select(text) %>%
  unnest_tokens(output = word, input = text) %>%
  anti_join(stop_words) %>%
  mutate(word = tolower(word)) 


parts_of_speech_ad <- parts_of_speech %>%
  filter(pos %in% c("Adjective", "Adverb", "Noun", "Verb"))

parole_sub2 <- parole_sub2 %>%
  left_join(parts_of_speech_ad, by = "word")
  
#n-gram and bigram (2 words)

```

```{r count-1}
parole_sub3 <- parole_sub2 %>%
  group_by(pos) %>%
  summarise(count = n())%>%
  arrange(desc(count)) %>%
  na.omit()
```

```{r Grouping by Adj and Adverb}
parole_sub4 <- parole_sub2 %>%
  group_by(word, pos) %>%
  summarise(count = n())%>%
  arrange(desc(count)) %>%
  na.omit()
```

```{r Attaching Sentiments to Words}
parole_sentiments <- get_sentiments()
parole_adj_adv <- parole_sub4 %>%
  left_join(parole_sentiments, by = "word")
# anti_join(parole_sentiments) 

parole_adj_adv[is.na(parole_adj_adv)] <- "neutral"
```

```{r count-2}
parole_sub5 <- parole_adj_adv %>%
  group_by(sentiment) %>%
  summarise(count = n())%>%
  arrange(desc(count)) %>%
  na.omit()
```


```{r top 10 positive versus negative sentiments}
top10_per_sentiment <- parole_adj_adv %>%
  group_by(sentiment) %>%
  slice_max(count, n = 10)
#make sure adverbs and adj aren't overlapping

```


```{r}
top10_per_sentiment <- parole_adj_adv %>%
  filter(pos == "Adjective" | pos == "Adverb")%>%
# distinct(word, .keep_all = TRUE) %>%
  filter(!duplicated(word)) %>%
  group_by(sentiment) %>%
  slice_max(count, n = 10)
```


```{r}
# libraries
library(packcircles)
library(ggplot2)
library(viridis)
library(ggiraph)

# Create data
data <- data.frame(group=paste("Group_", sample(letters, 70, replace=T), sample(letters, 70, replace=T), sample(letters, 70, replace=T), sep="" ), value=sample(seq(1,70),70)) 

# Add a column with the text you want to display for each bubble:
data$text <- paste("name: ",data$group, "\n", "value:", data$value, "\n", "You can add a story here!")
```

```{r circle packing try #1}
library(packcircles)
library(ggplot2)
library(dplyr)
library(tidyr)

data2 <- top10_per_sentiment %>%
  select(-pathString) %>%
  dplyr::arrange(-count)

head(data2)


# Formate data
pck <- circleProgressiveLayout(data2$count, sizetype="area")
head(pck)

# Following two datasets will be used in the plot
mydata <- cbind(data2, pck)

myPlotCord <- circleLayoutVertices(pck)

myPlotCord$id <- c(rep(1, 10), rep(2, 10), rep(3, 10))

#----------------------------------------

p1 <- ggplot()
p1 <- p1 + geom_polygon(data = myPlotCord, aes(x, y, group = id, fill=as.factor(id)))
p1 <- geom_text(data = mydata, aes(x, y, size=count, label = paste(word, "\n", count)))
p1
```


```{r circular packing diff app}
## Import libraries
library(tidyverse)
library(circlepackeR)  
library(hrbrthemes)
library(htmlwidgets)
library(data.tree)

## Import data
nestdict <- py$nestdict

## Prepare data format
nestdict$pathString <- paste("world", 
                             nestdict$Category, 
                             nestdict$Level, 
                             sep = "/")

population <- as.Node(nestdict)
 
## Make the plot
circlepackeR(population, 
             size = "Population", 
             color_min = "hsl(56,80%,80%)", 
             color_max = "hsl(341,30%,40%)")
```



```{r circle packing try #2}
# Circlepacker package
library(circlepackeR)         
# devtools::install_github("jeromefroe/circlepackeR") # If needed

# create a nested data frame giving the info of a nested dataset:
data <- data.frame(
  root=rep("root", 15),
  group=c(rep("group A",5), rep("group B",5), rep("group C",5)), 
  subgroup= rep(letters[1:5], each=3),
  subsubgroup=rep(letters[1:3], 5),
  value=sample(seq(1:15), 15)
)

# Change the format. This use the data.tree library. This library needs a column that looks like root/group/subgroup/..., so I build it
library(data.tree)
# Circlepacker package
library(circlepackeR)         
#devtools::install_github("jeromefroe/circlepackeR")
data$pathString <- paste("world", data$group, data$subgroup, data$subsubgroup, sep = "/")
population <- as.Node(data)

# Make the plot
circlepackeR(population, size = "value")

# You can custom the minimum and maximum value of the color range.
q <- circlepackeR(population, size = "value", color_min = "hsl(56,80%,80%)", color_max = "hsl(341,30%,40%)")

q

top10_per_sentiment$pathString <- paste("world", top10_per_sentiment$sentiment, top10_per_sentiment$pos, top10_per_sentiment$word, sep = "/")
population <- as.Node(top10_per_sentiment)

# Make the plot
circlepackeR(population, size = "count")

# You can custom the minimum and maximum value of the color range.
p <- circlepackeR(population, size = "count", color_min = "hsl(56,80%,80%)", color_max = "hsl(341,30%,40%)")

p

# save the widget
library(htmlwidgets)
saveWidget(p, file="circular_packing_circlepackeR2.html")
```


```{r circular packing try #3}
# Libraries
library(packcircles)
library(ggplot2)


# Source of code: 
# https://r-graph-gallery.com/305-basic-circle-packing-with-one-level.html
 
# Create data
data2 <- top10_per_sentiment %>%
  select(-pathString) %>%
  dplyr::arrange(-count)

head(data2)

 
# Generate the layout. This function return a dataframe with one line per bubble. 
# It gives its center (x and y) and its radius, proportional of the value
pack <- circleProgressiveLayout(data2$count, sizetype='area')
 
# We can add these packing information to the initial data frame
data3 <- cbind(data2, pack)
 
# Check that radius is proportional to value. We don't want a linear relationship, since it is the AREA that must be proportionnal to the value
# plot(data3$radius, data3$count)
 
# The next step is to go from one center + a radius to the coordinates of a circle that
# is drawn by a multitude of straight lines.
dat.gg <- circleLayoutVertices(pack, npoints=50)

dat.gg$sentiment <- paste(data3$sentiment)
 
# Make the plot
ggplot() + 
  
  # Make the bubbles
  geom_polygon(data = dat.gg, aes(x, y, group = id), colour = "black", alpha = 0.6) +
  
  # Add text in the center of each bubble + control its size
  geom_text(data = data3, aes(x, y, size=count, label = word)) +
  scale_size_continuous(range = c(1,4)) +
  
  # General theme:
  theme_void() + 
  theme(legend.position="none") +
  coord_equal()
  

```



```{r data.tree}
# Circlepacker package
library(circlepackeR)         
# devtools::install_github("jeromefroe/circlepackeR") # If needed

# create a treemap
# install.packages(data.tree)
library(data.tree)


## Prepare data format
top10_per_sentiment$pathString <- paste("world",
                                        top10_per_sentiment$sentiment, 
                                        top10_per_sentiment$pos, 
                                        top10_per_sentiment$word,
                                        sep = "/")
population <- as.Node(top10_per_sentiment)
print(population, "sentiment", "pos", "word", limit = 20)
 
## Make the plot
circlepackeR(population, 
             size = "count", 
             color_min = "hsl(56,80%,80%)", 
             color_max = "hsl(341,30%,40%)")

# You can custom the minimum and maximum value of the color range.
circlepackeR(population, size = "count", color_min = "hsl(56,80%,80%)", color_max = "hsl(341,30%,40%)", width = NULL, height = NULL)

```

