---
title: "parole_analysis_1"
author: "Ricky Sun"
date: "5/16/2022"
output: html_document
---

```{r}
library(hrbrthemes)
```


##Use parole_analysis_data_2

```{r}
parole_sub2 %>%
  count(word, sort = TRUE) %>%
  slice_max(n, n = 15) %>%
  mutate(word = reorder(word, n)) %>%
  # put `n` on the x-axis and `word` on the y-axis
  ggplot(aes(n, word)) +
  geom_col() +
  ggtitle("Most common words in Maine news around parole") +
  labs(subtitle = "from texts", y = "word", x = "count/frequency") +
  theme_minimal()
```


##Use parole_analysis_data_2

```{r}
common_negative_words <- parole_adj_adv %>%
  filter(pos == "Adjective") %>%
  filter(word != "guilty") %>%
  filter(sentiment == "negative") %>%
  group_by(pubtitle) %>%
  select(word, count) %>%
  top_n(n = 3) %>%
  ggplot(aes(count, word, fill = pubtitle)) +
  geom_col() +
  ggtitle("Most common words in Maine news around parole by press") +
  labs(y = "word") +
  theme_minimal()

common_negative_words
```

```{r}
parole1 %>%
    arrange(desc(count)) %>%
    ggplot(aes(count, word)) +
    geom_col() +
    ggtitle("Most common words in Maine news around parole") +
    labs(subtitle = "from texts", y = "word", x = "count/frequency") +
    theme_minimal()
```

##Use parole_analysis_data_2

```{r}
parole_sub8 <- parole_adj_adv %>%
  filter(pos == "Adjective" | pos == "Adverb") %>%
  filter(sentiment == "negative") %>%
  group_by(year, pubtitle, sentiment) %>%
  summarise(count = n())%>%
  arrange(desc(count)) %>%
  na.omit()


parole_sub8 %>%
  ggplot(aes(x=year, y=count, fill=pubtitle)) +
  geom_area() +
  ggtitle("frequency of negative adjectives or adverbs in Maine news around parole by press") 
```

```{r}
parole_sub11 %>%
      mutate(percentage_negative = negative/(negative + positive + neutral)) %>%
      mutate(percentage_positive = positive/(negative + positive + neutral)) %>%
      group_by(year, pubtitle) %>%
      arrange(desc(percentage_negative)) %>%
      na.omit() %>%
      #filter(sentiment == input$sentiment) %>%
      #filter(year %in% c(input$year)) %>%

      ggplot(aes(x=year, y=negative, fill=pubtitle)) +
      geom_area() +
      ggtitle("frequency of negative adjectives or adverbs in Maine news around parole by press") +
      theme_minimal()
```




##Use parole_analysis_data_2

```{r}
parole_sub9 <- parole_text %>%
  filter(pos == "Adjective" | pos == "Adverb") %>%
  filter(sentiment == "positive") %>%
  group_by(year, pubtitle, sentiment) %>%
  summarise(count = n())%>%
  arrange(desc(count)) %>%
  na.omit()

parole_sub9 %>%
  ggplot(aes(x=year, y=count, fill=pubtitle)) +
  geom_bar(stat="identity", position=position_dodge()) +
  scale_fill_viridis(discrete = TRUE) +
  theme_ipsum() +
  ggtitle("frequency of positive adjectives or adverbs in Maine news around parole by press") +
  theme_minimal()
```

```{r count-1}
parole_sub10 <- parole_adj_adv %>%
  filter(pos == "Adjective" | pos == "Adverb") %>%
  group_by(year, pubtitle, sentiment) %>%
  summarise(count = n())%>%
  arrange(desc(count)) %>%
  na.omit()
```

```{r}
parole_sub_wide <- parole_sub10 %>%
  pivot_wider(names_from = sentiment, values_from = count)
```


##Use parole_analysis_data_2

```{r}
parole_sub11 <- parole_sub_wide %>%
  mutate(percentage_negative = negative/(negative + positive + neutral)) %>%
  group_by(year, pubtitle) %>%
  arrange(desc(percentage_negative)) %>%
  na.omit()

parole_sub11 %>%
  ggplot(aes(x=year, y=percentage_negative, fill=pubtitle)) +
  geom_bar(stat="identity", position=position_dodge()) +
  scale_fill_viridis(discrete = TRUE) +
  theme_ipsum() +
  ggtitle("ratio of negative adjectives/adverbs occurance in Maine news around parole") +
  labs(subtitle = "by press") +
  theme_minimal()

#write_csv(parole_sub11, "parole_final2.csv")
```









