---
title: "parole_analysis_data_3"
author: "Ricky Sun"
date: "5/17/2022"
output: html_document
---

```{r ndividual Words and their parts of speech}
#install.packages("SnowballC")
#install.packages("dplyr")
library(SnowballC)
library(dplyr)
library(janitor)

parole_sub2 <- parole_sub %>%
  select(Abstract, year, pubtitle) %>%
  distinct(Abstract, year, pubtitle) %>%
  unnest_tokens(output = word, input = Abstract) %>%
  anti_join(stop_words) %>%
  mutate(word = tolower(word)) 

```

```{r}
parts_of_speech_ad <- parts_of_speech %>%
  filter(pos %in% c("Adjective", "Adverb", "Noun", "Verb"))

parole_sub2 <- parole_sub2 %>%
  left_join(parts_of_speech_ad, by = "word")
```


```{r count-1}
parole_sub3 <- parole_sub2 %>%
  group_by(year, pubtitle, pos) %>%
  summarise(count = n())%>%
  arrange(desc(count)) %>%
  na.omit()
```


```{r Grouping by Adj and Adverb}
parole_sub4 <- parole_sub2 %>%
  group_by(year, pubtitle, word, pos) %>%
  summarise(count = n())%>%
  arrange(desc(count)) %>%
  na.omit()
```

```{r Attaching Sentiments to Words}
parole_sentiments <- get_sentiments()
parole_abstract <- parole_sub4 %>%
  left_join(parole_sentiments, by = "word")
# anti_join(parole_sentiments) 

parole_abstract[is.na(parole_abstract)] <- "neutral"
```